// Auto-generated poet index
const GANJOOR_INDEX = [
  {file:"ganjoor-moulavi-divanshams.js",varName:"GANJOOR_POEMS_MOULAVI_DIVANSHAMS",poetName:"جلال الدین محمد مولوی",poetNickname:"مولانا",sizeKB:4868,lazy:true,sections:["دیوان شمس"]},
  {file:"ganjoor-saadi.js",varName:"GANJOOR_POEMS_SAADI",poetName:"سعدی شیرازی",poetNickname:"سعدی",sizeKB:3005,lazy:true,sections:["بوستان","دیوان اشعار","رباعیات","غزلیات","قطعات","مجالس پنجگانه","مقدمهٔ علی بن احمد بن ابی بکر بیستون (گردآورندهٔ دیوان شیخ سعدی، ۷۳۴ هجری قمری)","ملحقات و مفردات","مواعظ","گلستان"]},
  {file:"ganjoor-attar.js",varName:"GANJOOR_POEMS_ATTAR",poetName:"عطار نیشابوری",poetNickname:"عطار",sizeKB:1372,lazy:true,sections:["الهی نامه","تذکرة الأولیاء","ترجیعات","غزلیات","مختارنامه","مصیبت نامه","منطق‌الطیر"]},
  {file:"ganjoor-saeb.js",varName:"GANJOOR_POEMS_SAEB",poetName:"صائب",poetNickname:"صائب",sizeKB:1356,lazy:true,sections:["تک‌بیتهای برگزیده","غزلیات","متفرقات","مطالع"]},
  {file:"ganjoor-moulavi-masnavi.js",varName:"GANJOOR_POEMS_MOULAVI_MASNAVI",poetName:"جلال الدین محمد مولوی",poetNickname:"مولانا",sizeKB:1277,lazy:true,sections:["مثنوی معنوی"]},
  {file:"ganjoor-hafez.js",varName:"GANJOOR_POEMS_HAFEZ",poetName:"حافظ شیرازی",poetNickname:"حافظ",sizeKB:1028,lazy:true,sections:["اشعار منتسب","رباعیات","ساقی‌نامه","غزلیات","قصاید","قطعات","مثنوی (الا ای آهوی وحشی)"]},
  {file:"ganjoor-ferdousi.js",varName:"GANJOOR_POEMS_FERDOUSI",poetName:"ابوالقاسم فردوسی",poetNickname:"فردوسی",sizeKB:715,lazy:true,sections:["شاهنامه","هجونامه (منتسب)"]},
  {file:"ganjoor-parvin.js",varName:"GANJOOR_POEMS_PARVIN",poetName:"پروین اعتصامی",poetNickname:"پروین اعتصامی",sizeKB:561,lazy:true,sections:["قصاید","مثنویات، تمثیلات و مقطعات"]},
  {file:"ganjoor-vahshi.js",varName:"GANJOOR_POEMS_VAHSHI",poetName:"وحشی بافقی",poetNickname:"وحشی بافقی",sizeKB:362,lazy:true,sections:["ترکیبات","خلد برین","رباعیات","غزلیات","فرهاد و شیرین"]},
  {file:"ganjoor-bidel.js",varName:"GANJOOR_POEMS_BIDEL",poetName:"بیدل دهلوی",poetNickname:"بیدل دهلوی",sizeKB:356,lazy:true,sections:["غزلیات"]},
  {file:"ganjoor-khayyam.js",varName:"GANJOOR_POEMS_KHAYYAM",poetName:"خیام نیشابوری",poetNickname:"خیام",sizeKB:284,lazy:true,sections:["ترانه‌های خیام به انتخاب و روایت صادق هدایت","رباعیات","رباعیات خیام به پژوهش سیدعلی میرافضلی"]},
  {file:"ganjoor-bahar.js",varName:"GANJOOR_POEMS_BAHAR",poetName:"ملک‌الشعرا بهار",poetNickname:"ملک‌الشعرا بهار",sizeKB:281,lazy:true,sections:["ترکیبات","غزلیات","قصاید","قطعات","مثنویات","مسمطات"]},
  {file:"ganjoor-sanaee.js",varName:"GANJOOR_POEMS_SANAEE",poetName:"سنایی غزنوی",poetNickname:"سنایی",sizeKB:262,lazy:true,sections:["رباعیات","غزلیات","قصاید","قصاید و قطعات"]},
  {file:"ganjoor-rahi.js",varName:"GANJOOR_POEMS_RAHI",poetName:"رهی معیری",poetNickname:"رهی معیری",sizeKB:198,lazy:true,sections:["ابیات پراکنده","رباعیها","غزلها - جلد اول","غزلها - جلد دوم","غزلها - جلد سوم","غزلها - جلد چهارم","منظومه‌ها","چند تغزل","چند قطعه"]},
  {file:"ganjoor-iraj.js",varName:"GANJOOR_POEMS_IRAJ",poetName:"ایرج میرزا",poetNickname:"ایرج میرزا",sizeKB:136,lazy:true,sections:["غزل‌ها","قصیده‌ها","قطعه‌ها","مثنوی‌ها"]},
  {file:"ganjoor-eraghi.js",varName:"GANJOOR_POEMS_ERAGHI",poetName:"عراقی",poetNickname:"عراقی",sizeKB:126,lazy:true,sections:["ترجیعات","رباعیات","عشاق‌نامه","غزلیات"]},
  {file:"ganjoor-khaghani.js",varName:"GANJOOR_POEMS_KHAGHANI",poetName:"خاقانی شروانی",poetNickname:"خاقانی",sizeKB:122,lazy:true,sections:["رباعیات","غزلیات","قصاید"]},
  {file:"ganjoor-forooghi.js",varName:"GANJOOR_POEMS_FOROOGHI",poetName:"فروغی بسطامی",poetNickname:"فروغی بسطامی",sizeKB:117,lazy:true,sections:["غزلیات"]},
  {file:"ganjoor-iqbal.js",varName:"GANJOOR_POEMS_IQBAL",poetName:"اقبال لاهوری",poetNickname:"اقبال لاهوری",sizeKB:117,lazy:true,sections:["جاویدنامه","رموز بیخودی","زبور عجم","پس چه باید کرد؟","پیام مشرق"]},
  {file:"ganjoor-helali.js",varName:"GANJOOR_POEMS_HELALI",poetName:"هلالی جغتایی",poetNickname:"هلالی جغتایی",sizeKB:109,lazy:true,sections:["غزلیات"]},
  {file:"ganjoor-nezami.js",varName:"GANJOOR_POEMS_NEZAMI",poetName:"نظامی گنجوی",poetNickname:"نظامی",sizeKB:102,lazy:true,sections:["خمسه"]},
  {file:"ganjoor-anvari.js",varName:"GANJOOR_POEMS_ANVARI",poetName:"انوری ابیوردی",poetNickname:"انوری",sizeKB:92,lazy:true,sections:["غزلیات","مقطعات"]},
  {file:"ganjoor-eshghi.js",varName:"GANJOOR_POEMS_ESHGHI",poetName:"میرزاده عشقی",poetNickname:"میرزاده عشقی",sizeKB:62,lazy:true,sections:["غزلیات و قصاید","مثنویات","مقطعات","نوروزی نامه","هزلیات"]},
  {file:"ganjoor-khajoo.js",varName:"GANJOOR_POEMS_KHAJOO",poetName:"خواجوی کرمانی",poetNickname:"خواجوی کرمانی",sizeKB:27,lazy:false,sections:["بدایع الجمال","صنایع الکمال"]},
  {file:"ganjoor-moulavi-fihimafih.js",varName:"GANJOOR_POEMS_MOULAVI_FIHIMA_FIH",poetName:"جلال الدین محمد مولوی",poetNickname:"مولانا",sizeKB:25,lazy:false,sections:["فیه ما فیه"]},
  {file:"ganjoor-obeyd.js",varName:"GANJOOR_POEMS_OBEYD",poetName:"عبید زاکانی",poetNickname:"عبید زاکانی",sizeKB:19,lazy:false,sections:["دیوان اشعار","رباعیات","عشاق‌نامه","غزلیات","موش و گربه"]},
  {file:"ganjoor-seyf.js",varName:"GANJOOR_POEMS_SEYF",poetName:"سیف فرغانی",poetNickname:"سیف فرغانی",sizeKB:4,lazy:false,sections:["غزلیات","قصاید و قطعات"]},
  {file:"ganjoor-salim.js",varName:"GANJOOR_POEMS_SALIM",poetName:"سلیم تهرانی",poetNickname:"سلیم تهرانی",sizeKB:1,lazy:false,sections:["رباعیات","غزلیات"]},
];
